preload = /home/teo/wallpaper/bodies_in_rythm.jpg

wallpaper = ,/home/teo/wallpaper/bodies_in_rythm.jpg

#enable splash text rendering over the wallpaper
splash = false
 
#fully disable ipc
# ipc = off
