# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/Configuring/Animations/

animations { 
  enabled = yes
  animation = windows, 1, 5, default, popin 80%
  animation = fade, 1, 2, default
  animation = workspacesIn, 1, 2, default, slide
  animation = workspacesIn, 1, 2, default, slide
}
