# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar
# $applauncher = walker
$applauncher = anyrun
$terminal = kitty
$browser = zen-browser

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
