# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

#$cachylgreen = rgba(82dcccff)
$cachylgreen = rgba(b8bb26ff)
#$cachymgreen = rgba(00aa84ff)
$cachymgreen = rgba(00aa84ff)
#$cachydgreen = rgba(007d6fff)
$cachydgreen = rgba(007d6fff)
#$cachylblue = rgba(01ccffff)
$cachylblue = rgba(01ccffff)
#$cachymblue = rgba(182545ff)
$cachymblue = rgba(b9bb2540)
#$cachydblue = rgba(111826ff)
$cachydblue = rgba(111826ff)
#$cachywhite = rgba(ffffffff)
$cachywhite = rgba(ffffffff)
#$cachygrey = rgba(ddddddff)
$cachygrey = rgba(ddddddff)
#$cachygray = rgba(798bb2ff)
$cachygray = rgba(798bb2ff)
